-- taken from LazyVim
--  https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/init.lua#L14
return {
    icons = {
        ui = {
            selected = "󰫙 ",
            word = "",
            clock = " ",
        },
        diagnostics = {
            [vim.diagnostic.severity.ERROR] = " ",
            [vim.diagnostic.severity.WARN] = " ",
            [vim.diagnostic.severity.INFO] = " ",
            [vim.diagnostic.severity.HINT] = " ",
        },
        git = {
            added = " ",
            modified = " ",
            removed = " ",
        },
        kinds = {
            -- TODO: migrate to mini.icons
            array = " ",
            boolean = " ",
            class = " ",
            color = " ",
            constant = " ",
            constructor = " ",
            copilot = " ",
            enum = " ",
            enummember = " ",
            event = " ",
            field = " ",
            file = " ",
            folder = " ",
            ["function"] = " ",
            interface = " ",
            key = " ",
            keyword = " ",
            method = " ",
            module = " ",
            namespace = " ",
            null = " ",
            number = " ",
            object = " ",
            operator = " ",
            package = " ",
            property = " ",
            reference = " ",
            snippet = " ",
            string = " ",
            struct = " ",
            text = " ",
            typeparameter = " ",
            unit = " ",
            value = " ",
            variable = " ",
        },
    },
}
